# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 153506d769e6c228f98c94d2828bb24f0370820d87ea417cd67e495beae442d05840e0ce57df15a3c8450abba92ebca1f0f56b5dc8701041e6c3bbcaa21bd8d4

test:
  secret_key_base: 7bd8b2c223a3e00580c3dd80bedb7c83169952f35834501f6fef5685895e12047823b568da2d1a3cbaac817044dcabf368698994cdaffa72eaf86710e7562caf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
